### ISSUE TITLE
[SH-146] UserController UserImageController 분류 관련

### ISSUE THREAD

**Issue by elyudwo** [study-hub-inu/study-hub-server#39]
UserController 한개의 클래스에서 CRUD + Image CD 까지 구현하려니 클래스 사이즈가 너무 커지는것 같네요.

현재 Image와 기본 CRUD 의 Controller와 Service를 분리 시킨 상태인데 동우님 생각은 어떠신지요??

**Comment by wellbeing-dough** [comment]
저는 이미지 업로드 api하나 -> imageUrl 반환해줌 -> 프론트가 이미지 url을 사용해서 유저 정보 수정 put으로 생각했는데 지금 pr올린 방식도 괜찮은거같아요

**Comment by elyudwo** [comment]
good!
